import './globals.css'
import { Providers } from "@/redux/provider";
import Header from '@/components/header';
import Footer from '@/components/footer';

export const metadata = {
  title: 'Next JS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>        
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
